// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectVenvs(arg1:string):Promise<Array<string>>;

export function GetCategories():Promise<Array<string>>;

export function GetEnvConfig():Promise<main.EnvConfig>;

export function GetTools():Promise<Array<main.ToolConfig>>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RunPtyTool(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SaveCategories(arg1:Array<string>):Promise<void>;

export function SaveEnvConfig(arg1:main.EnvConfig):Promise<void>;

export function SaveTools(arg1:Array<main.ToolConfig>):Promise<void>;

export function StartTool(arg1:string,arg2:boolean):Promise<string>;

export function StopPtySession(arg1:string):Promise<void>;
