// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectVenvs(arg1) {
  return window['go']['main']['App']['DetectVenvs'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetEnvConfig() {
  return window['go']['main']['App']['GetEnvConfig']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RunPtyTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunPtyTool'](arg1, arg2, arg3);
}

export function SaveCategories(arg1) {
  return window['go']['main']['App']['SaveCategories'](arg1);
}

export function SaveEnvConfig(arg1) {
  return window['go']['main']['App']['SaveEnvConfig'](arg1);
}

export function SaveTools(arg1) {
  return window['go']['main']['App']['SaveTools'](arg1);
}

export function StartTool(arg1, arg2) {
  return window['go']['main']['App']['StartTool'](arg1, arg2);
}

export function StopPtySession(arg1) {
  return window['go']['main']['App']['StopPtySession'](arg1);
}
